import Head from 'next/head'
import Image from 'next/image'

const MainLayout = ({children}) => 
  <div className='Container'>
    <Head>
      <title>BogoGames</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css?family=Lato:300,700|Prata" rel="stylesheet" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className="SiteHeader">
      <div class="pure-menu pure-menu-horizontal">
        <a href="/" class="pure-menu-heading">Bogogames</a>
        <ul class="pure-menu-list">
          <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link">Noticias</a></li>
          <li class="pure-menu-item"><a href="#" class="pure-menu-link">Reseñas</a></li>
          <li class="pure-menu-item"><a href="#" class="pure-menu-link">Mapa</a></li>
          <li class="pure-menu-item"><a href="#" class="pure-menu-link">Contacto</a></li>
        </ul>
      </div>
    </header>
    <main>{children}</main>
    <footer>
    </footer>
  </div>

export default MainLayout;
